import React from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { ArrowRight, CalendarHeart, ChevronRight, Clock, Heart, Instagram, MapPin, MessageCircle, Phone, Sparkles, Star, Truck, UtensilsCrossed } from 'lucide-react';
import './styles.css';

const WA = 'https://wa.me/522211873410?text=Hola%20Cuore%20Italiano%2C%20quiero%20hacer%20un%20pedido%20directo';
const MAPS = 'https://www.google.com.mx/maps/search/Av.+6+Ote.+6,+Centro,+Cholula,+Puebla';
const IMG = {
  hero: 'https://cuore-italiano.com/wp-content/uploads/2026/01/WhatsApp-Image-2026-01-22-at-10.03.29-AM-1.jpeg',
  scoop: 'https://cuore-italiano.com/wp-content/uploads/2026/01/helado2.jpg',
  cone: 'https://cuore-italiano.com/wp-content/uploads/2026/01/CUORE-04.jpg',
  cup: 'https://cuore-italiano.com/wp-content/uploads/2026/01/CUORE-01.jpg',
  drink: 'https://cuore-italiano.com/wp-content/uploads/2026/01/CUORE-09.jpg',
  event: 'https://cuore-italiano.com/wp-content/uploads/2026/01/PHOTO-2026-01-12-12-46-34.jpeg',
};
const flavors = ['Pistache', 'Nogada', 'Nocciola', 'Tiramisú', 'Lavanda', 'Jamaica & albahaca', 'Frutti di Bosco', 'Chocolate sorbetto'];
const apps = [
  ['Didi Food', 'https://www.didi-food.com/'], ['Uber Eats', 'https://www.ubereats.com/'], ['Rappi', 'https://www.rappi.com.mx/']
];
function A({href=WA, children, secondary=false, className=''}){return <a href={href} target={href.startsWith('http')?'_blank':undefined} className={`btn ${secondary?'btn2':'btn1'} ${className}`}>{children}</a>}
function Img({src, alt, className=''}){return <img src={src} alt={alt} loading="lazy" className={`img ${className}`} onError={(e)=>e.currentTarget.classList.add('imgFallback')} />}
function Reveal({children, className=''}){return <motion.div initial={{opacity:0,y:34}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-80px'}} transition={{duration:.75,ease:[.22,1,.36,1]}} className={className}>{children}</motion.div>}
function Header(){return <header className="header"><a href="#top" className="brand"><img src="/assets/cuore-logo.svg" alt="Cuore Italiano"/></a><nav><a href="#gelato">Gelato</a><a href="#pedido">Pedido directo</a><a href="#eventos">Eventos</a><a href="#ubicacion">Ubicación</a></nav><A className="hide-sm"><MessageCircle size={18}/> Ordenar directo</A></header>}
function Hero(){return <section id="top" className="hero"><div className="heroBg"/><div className="shell heroGrid"><Reveal className="heroText"><span className="eyebrow"><Sparkles size={16}/> Gelato artesanal italiano en Cholula</span><h1>Tu momento mágico, servido directo por Cuore.</h1><p>Cremosidad perfecta, sabores intensos e ingredientes naturales. Pide directo por WhatsApp y recibe el gelato con el cuidado de casa.</p><div className="ctaRow"><A><MessageCircle/> Ordenar directo por WhatsApp</A><A secondary href="#gelato">Explorar sabores <ArrowRight/></A></div><div className="proof"><span>Desde 2016</span><span>+100 sabores creados</span><span>Sin bases prehechas</span></div></Reveal><Reveal className="heroCard"><Img src={IMG.hero} alt="Gelato artesanal Cuore Italiano"/><div className="floatCard"><Heart/> Natural, artesanal y preparado con amore</div></Reveal></div></section>}
function Why(){const items=[['100% natural','Sin saborizantes ni colorantes artificiales.'],['Hecho desde cero','Recetas propias, ingredientes frescos y procesos cuidados.'],['Más intenso','Menos grasa, menos azúcar y mucho más sabor que un helado común.']];return <section className="section cream"><div className="shell"><Reveal><span className="kicker">No es helado, es gelato</span><h2>El respiro dulce que convierte cualquier día en recuerdo.</h2></Reveal><div className="cards">{items.map(([t,d],i)=><Reveal className="card" key={t}><span className="num">0{i+1}</span><h3>{t}</h3><p>{d}</p></Reveal>)}</div></div></section>}
function Showcase(){return <section id="gelato" className="section dark"><div className="shell split"><Reveal><span className="kicker">Producto estrella</span><h2>Gelatos, sorbettos, bebidas y postres con carácter italiano.</h2><p className="lead">Clásicos, sabores top, opciones sin azúcar y temporadas especiales. Disfrútalos en tienda o llévalos en medios litros.</p><div className="chips">{flavors.map(f=><span key={f}>{f}</span>)}</div><A href={WA}><MessageCircle/> Preguntar sabores de hoy</A></Reveal><Reveal className="mosaic"><Img src={IMG.scoop} alt="Sabores de gelato"/><Img src={IMG.cone} alt="Gelato Cuore"/><Img src={IMG.drink} alt="Bebidas Cuore"/><Img src={IMG.cup} alt="Postres y gelato"/></Reveal></div></section>}
function DirectOrder(){return <section id="pedido" className="section order"><div className="shell orderBox"><Reveal><span className="eyebrow"><Truck size={16}/> Pedido preferente</span><h2>Ordena directo con Cuore Italiano.</h2><p>La forma más cercana, rápida y cuidada: escríbenos por WhatsApp, confirma sabores disponibles y recibe atención directa del equipo.</p><ul><li><ChevronRight/> Atención directa</li><li><ChevronRight/> Medios litros preparados a temperatura ideal</li><li><ChevronRight/> Gelato, bebidas y postres sujetos a disponibilidad</li></ul></Reveal><Reveal className="orderCta"><div className="bigIcon"><MessageCircle/></div><h3>¿Antojo ahora?</h3><p>Abre WhatsApp y pide tu momento mágico.</p><A><Phone/> Pedir por WhatsApp</A></Reveal></div></section>}
function Apps(){return <section className="section apps"><div className="shell"><Reveal className="center"><span className="kicker">También disponible</span><h2>Apps de delivery, como segunda opción.</h2><p className="lead">Si prefieres pedir desde tu app favorita, también puedes encontrarnos ahí.</p></Reveal><div className="appGrid">{apps.map(([name,url])=><a className="appCard" href={url} target="_blank" key={name}><UtensilsCrossed/><b>{name}</b><span>Ordenar en app</span></a>)}</div></div></section>}
function Events(){return <section id="eventos" className="section event"><div className="shell split"><Reveal className="eventImg"><Img src={IMG.event} alt="Gelato para eventos Cuore Italiano"/></Reveal><Reveal><span className="kicker">Vamos a tu evento</span><h2>Haz que tu celebración sepa inolvidable.</h2><p className="lead">Tú eliges los sabores; Cuore lleva la magia. Cotizaciones para eventos de cualquier tamaño, con servicio a partir de 50 invitados.</p><div className="mini"><span><CalendarHeart/> Bodas</span><span><Star/> Cumpleaños</span><span><Sparkles/> Empresas</span></div><A href="https://wa.me/522211873410?text=Hola%20Cuore%20Italiano%2C%20quiero%20cotizar%20gelato%20para%20un%20evento"><MessageCircle/> Solicitar cotización</A></Reveal></div></section>}
function StoryLocation(){return <section id="ubicacion" className="section cream"><div className="shell storyGrid"><Reveal className="story"><span className="kicker">Nuestra historia</span><h2>Un sueño italiano que encontró casa en Puebla.</h2><p>Nacimos de una pasión heredada y del deseo de llevar a México el verdadero gelato italiano. Desde 2016 elaboramos cada receta sin atajos, con ingredientes frescos, procesos artesanales y amor por los pequeños grandes placeres.</p></Reveal><Reveal className="location"><MapPin/><h3>Visítanos en Cholula</h3><p>Av. 6 Ote. 6, Centro, Cholula, Puebla</p><p><Clock/> Pregunta horarios y sabores disponibles por WhatsApp.</p><A href={MAPS} secondary>Cómo llegar <ArrowRight/></A></Reveal></div></section>}
function Footer(){return <footer className="footer"><div className="shell footGrid"><div><img src="/assets/cuore-logo.svg" alt="Cuore Italiano"/><p>Gelato artesanal italiano para tu pausa, tu antojo y tus celebraciones.</p></div><div><h4>Ordena</h4><a href={WA}>Pedido directo WhatsApp</a><a href="#pedido">Cómo pedir directo</a><a href="#eventos">Cotizar evento</a></div><div><h4>Contacto</h4><a href="mailto:cuoreitaliano.gelato@gmail.com">cuoreitaliano.gelato@gmail.com</a><a href="https://www.instagram.com/cuoreitaliano.gelato/" target="_blank"><Instagram/> @Cuoreitaliano.gelato</a><a href={MAPS} target="_blank">Av. 6 Ote. 6, Cholula</a></div></div><a className="mobileWa" href={WA}><MessageCircle/> Ordenar directo</a></footer>}
function App(){return <><Header/><Hero/><Why/><Showcase/><DirectOrder/><Apps/><Events/><StoryLocation/><Footer/></>}

createRoot(document.getElementById('root')).render(<App/>);
